function [compartmentPositions,LineSourceModifierArr] = ...
  setupLFPConstants(NeuronArr, RecordingInfo, ...
                    SimulationSettings, TissueProperties)

% Generate electrode tip positions
meaX = RecordingInfo.meaXpositions;
meaY = RecordingInfo.meaYpositions;
meaZ = RecordingInfo.meaZpositions;
RecordingInfo.electrodePositionArr =  ...
  generateElectrodePositions(meaX, meaY, meaZ);

storeCompartmentPositions = true;

% Calculate line source modifier constants for electrode array
if SimulationSettings.parallelSim
  spmd
    [compartmentPositions, LineSourceModifierArr] = ...
    calculateLineSourceModifiers(storeCompartmentPositions, ...
    NeuronArr, ...
    RecordingInfo, ...
    SimulationSettings, ...
    TissueProperties);
  end
else
  [compartmentPositions, LineSourceModifierArr] = ...
    calculateLineSourceModifiers(storeCompartmentPositions, ...
    NeuronArr, ...
    RecordingInfo, ...
    SimulationSettings, ...
    TissueProperties);
end